#!/usr/bin/env bash
for python_version in 2.7.12 2.7.14 3.6.3 3.6.5; do
    CFLAGS="-I$(brew --prefix readline)/include -I$(brew --prefix openssl)/include -I$(xcrun --show-sdk-path)/usr/include" \
        LDFLAGS="-L$(brew --prefix readline)/lib -L$(brew --prefix openssl)/lib" \
        PYTHON_CONFIGURE_OPTS=--enable-unicode=ucs2 pyenv install -s $python_version
done
